# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 04:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('readgood', '0002_auto_20170710_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='readgood.Author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='readgood.Publisher'),
            preserve_default=False,
        ),
    ]
