# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 21:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('readgood', '0003_auto_20170710_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='readgood.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BooksRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readgood.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BooksToRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readgood.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(max_length=255, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('favorite_author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='readgood.Author')),
                ('favorite_book',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='readgood.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(
                    choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'),
                             (9, '9'), (10, '10')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readgood.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookstoread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booksread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        #  made me change to set literal. If there are problems with this migration, that is why.
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='bookstoread',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='booksread',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('name', 'year')},
        ),
    ]
