# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('readgood', '0005_auto_20170714_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(max_length=2),
        ),
    ]
