# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('readgood', '0006_auto_20170714_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(
                choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'),
                         (9, '9'), (10, '10')]),
        ),
    ]
